apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-dmrr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-dmrr
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-dmrr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-dmrr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-dmrr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-csxu-tenant/status-quarkus-io/statusquarkusio-dmrr@sha256:b78d983b4a1e9c6add4b19fb1c0b280274e8c90949a8020c6d1a702d1c3680cb
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
